### ISSUE TITLE
User cannot view or edit own profile

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#806]
I have this replicating with the latest db dump from yesterday for a particular user.

When he tries to go to his profile it says "this profile is private".

In the database private is set to true and he has no hidden fields.

**Comment by ckiss** [comment]
@tangentfairy this seems fixed by the changes made here:
https://github.com/CoderDojo/cp-zen-platform/pull/749 & https://github.com/CoderDojo/cp-users-service/pull/171

**Comment by tangentfairy** [comment]
It still happens for me for the specific user mentioned in that email. Let me know tomorrow and we can screenshare.

**Comment by ckiss** [comment]
@tangentfairy have you still been able to reproduce this in the morning?

**Comment by tangentfairy** [comment]
Still happening, I sent you a dm with the info

**Comment by tangentfairy** [comment]
Fixed now, Laura is getting back to the user.
